CREATE TABLE SPORTSCARS (
         YEAR  NUMBER(4,0) NOT NULL,
         CONSTRAINT PK_Person PRIMARY KEY(YEAR),
         MAKE VARCHAR2(20),
         MODEL VARCHAR2(20),
         PRICE DECIMAL(10, 2));